description = "Core files of OpenTerrainGenerator"

dependencies {
    compileOnly 'org.projectlombok:lombok:1.18.32'
    annotationProcessor 'org.projectlombok:lombok:1.18.32'

    // Provided by Minecraft
    compileOnlyApi("it.unimi.dsi:fastutil:8.2.1")
    compileOnlyApi('com.google.guava:guava:33.0.0-jre')
}
