org.gradle.parallel=true
org.gradle.caching=true
org.gradle.jvmargs=-Xmx4G

minecraft_version=1.20.1
enabled_platforms=fabric

archive_base_name=otg
otg_group=com.pg85.otg
otg_version=0.2.0-dev9
maven_group=com.pg85.otg

architectury_version=9.1.12

fabric_loader_version=0.15.11
fabric_api_version=0.90.4+1.20.1

forge_version=1.20.1-47.2.1

java_version=17

loom_accessWidener_path="src/main/resources/META-INF/otg.accesswidener"

shadow_version='8.3.0'
