org.gradle.parallel=true
org.gradle.caching=true
org.gradle.jvmargs=-Xmx4G
javaVersion=19

# Access these properties using "${rootProject.extra['minecraftVersion']}"

# https://fabricmc.net/develop/
minecraftVersion=1.20.1
yarnMappings=1.20.1+build.10
fabricLoaderVersion=0.15.6

# Fabric api
fabricApiVersion=0.90.4+1.20.1
