import org.gradle.internal.jvm.Jvm

// Build script for the Common parts of OpenTerrainGenerator
buildscript {
	repositories {
		mavenCentral()
		gradlePluginPortal()
	}
	dependencies {
		classpath "com.gradleup.shadow:shadow-gradle-plugin:${shadowVersion}"
	}
}

apply plugin: 'java'
apply plugin: 'com.gradleup.shadow'

// Project properties
archivesBaseName = "openterraingenerator-common"
description = "Core files of OpenTerrainGenerator"

repositories
{
    mavenLocal()
    mavenCentral()
}

println "Running java version: " + Jvm.current().getJavaHome()

dependencies
{
    implementation (
		'com.fasterxml.jackson.core:jackson-annotations:2.17.2',
		'com.fasterxml.jackson.core:jackson-core:2.17.2',
		'com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:2.17.2',
		'com.fasterxml.jackson.core:jackson-databind:2.17.2',
		'org.yaml:snakeyaml:2.2',
		'org.apache.commons:commons-lang3:3.4'
    )	
}

shadowJar {
    dependencies {
		include dependency(':jackson-annotations')
		include dependency(':jackson-core')
		include dependency(':jackson-dataformat-yaml')
		include dependency(':jackson-databind')
		include dependency(':snakeyaml')
		include dependency(':commons-lang3')
    }
	relocate 'com.fasterxml.jackson', 'com.pg85.otg.shaded.fasterxml.jackson'
	relocate 'org.apache', 'com.pg85.otg.shaded.org.apache'
	relocate 'org.yaml', 'com.pg85.otg.shaded.org.yaml'
	archiveFileName = project.archivesBaseName + '-' + project.version + '.jar'
	destinationDirectory = project.layout.buildDirectory.dir('dists')
}

build.finalizedBy(shadowJar)