package com.pg85.otg.shared.tags;

import lombok.Getter;

@Getter
public enum OTGBiomeTagPath {
    IS_COLD_END("is_cold/end"),
    IS_COLD_NETHER("is_cold/nether"),
    IS_COLD_OVERWORLD("is_cold/overworld"),
    IS_DENSE_VEGETATION_END("is_dense_vegetation/end"),
    IS_DENSE_VEGETATION_NETHER("is_dense_vegetation/nether"),
    IS_DENSE_VEGETATION_OVERWORLD("is_dense_vegetation/overworld"),
    IS_DRY_END("is_dry/end"),
    IS_DRY_NETHER("is_dry/nether"),
    IS_DRY_OVERWORLD("is_dry/overworld"),
    IS_HOT_END("is_hot/end"),
    IS_HOT_NETHER("is_hot/nether"),
    IS_HOT_OVERWORLD("is_hot/overworld"),
    IS_MOUNTAIN_PEAK("is_mountain/peak"),
    IS_MOUNTAIN_SLOPE("is_mountain/slope"),
    IS_SPARSE_VEGETATION_END("is_sparse_vegetation/end"),
    IS_SPARSE_VEGETATION_NETHER("is_sparse_vegetation/nether"),
    IS_SPARSE_VEGETATION_OVERWORLD("is_sparse_vegetation/overworld"),
    IS_TEMPERATE_END("is_temperate/end"),
    IS_TEMPERATE_NETHER("is_temperate/nether"),
    IS_TEMPERATE_OVERWORLD("is_temperate/overworld"),
    IS_TREE_CONIFEROUS("is_tree/coniferous"),
    IS_TREE_DECIDUOUS("is_tree/deciduous"),
    IS_TREE_JUNGLE("is_tree/jungle"),
    IS_TREE_SAVANNA("is_tree/savanna"),
    IS_WET_END("is_wet/end"),
    IS_WET_NETHER("is_wet/nether"),
    IS_WET_OVERWORLD("is_wet/overworld"),
    PRIMARY_WOOD_TYPE_ACACIA("primary_wood_type/acacia"),
    PRIMARY_WOOD_TYPE_BAMBOO("primary_wood_type/bamboo"),
    PRIMARY_WOOD_TYPE_BIRCH("primary_wood_type/birch"),
    PRIMARY_WOOD_TYPE_CHERRY("primary_wood_type/cherry"),
    PRIMARY_WOOD_TYPE_CRIMSON("primary_wood_type/crimson"),
    PRIMARY_WOOD_TYPE_DARK_OAK("primary_wood_type/dark_oak"),
    PRIMARY_WOOD_TYPE_JUNGLE("primary_wood_type/jungle"),
    PRIMARY_WOOD_TYPE_MANGROVE("primary_wood_type/mangrove"),
    PRIMARY_WOOD_TYPE_OAK("primary_wood_type/oak"),
    PRIMARY_WOOD_TYPE_PALE_OAK("primary_wood_type/pale_oak"),
    PRIMARY_WOOD_TYPE_SPRUCE("primary_wood_type/spruce"),
    PRIMARY_WOOD_TYPE_WARPED("primary_wood_type/warped"),
    HIDDEN_FROM_LOCATOR_SELECTION("hidden_from_locator_selection"),
    IS_AQUATIC("is_aquatic"),
    IS_AQUATIC_ICY("is_aquatic_icy"),
    IS_BADLANDS("is_badlands"),
    IS_BEACH("is_beach"),
    IS_BIRCH_FOREST("is_birch_forest"),
    IS_CAVE("is_cave"),
    IS_COLD("is_cold"),
    IS_DARK_FOREST("is_dark_forest"),
    IS_DEAD("is_dead"),
    IS_DEEP_OCEAN("is_deep_ocean"),
    IS_DENSE_VEGETATION("is_dense_vegetation"),
    IS_DESERT("is_desert"),
    IS_DRY("is_dry"),
    IS_END("is_end"),
    IS_FLORAL("is_floral"),
    IS_FLOWER_FOREST("is_flower_forest"),
    IS_FOREST("is_forest"),
    IS_HILL("is_hill"),
    IS_HOT("is_hot"),
    IS_ICY("is_icy"),
    IS_JUNGLE("is_jungle"),
    IS_LUSH("is_lush"),
    IS_MAGICAL("is_magical"),
    IS_MOUNTAIN("is_mountain"),
    IS_MUSHROOM("is_mushroom"),
    IS_NETHER("is_nether"),
    IS_NETHER_FOREST("is_nether_forest"),
    IS_OCEAN("is_ocean"),
    IS_OLD_GROWTH("is_old_growth"),
    IS_OUTER_END_ISLAND("is_outer_end_island"),
    IS_OVERWORLD("is_overworld"),
    IS_PLAINS("is_plains"),
    IS_PLATEAU("is_plateau"),
    IS_RARE("is_rare"),
    IS_RIVER("is_river"),
    IS_SANDY("is_sandy"),
    IS_SAVANNA("is_savanna"),
    IS_SHALLOW_OCEAN("is_shallow_ocean"),
    IS_SNOWY("is_snowy"),
    IS_SNOWY_PLAINS("is_snowy_plains"),
    IS_SPARSE_VEGETATION("is_sparse_vegetation"),
    IS_SPOOKY("is_spooky"),
    IS_STONY_SHORES("is_stony_shores"),
    IS_SWAMP("is_swamp"),
    IS_TAIGA("is_taiga"),
    IS_TEMPERATE("is_temperate"),
    IS_UNDERGROUND("is_underground"),
    IS_VOID("is_void"),
    IS_WASTELAND("is_wasteland"),
    IS_WET("is_wet"),
    IS_WINDSWEPT("is_windswept"),
    NO_DEFAULT_MONSTERS("no_default_monsters"),
    PRIMARY_WOOD_TYPE("primary_wood_type");

    private final String path;

    OTGBiomeTagPath(String path) {
        this.path = path;
    }

}
