description = "Core files of OpenTerrainGenerator"

dependencies {
    api(project(":common:common-util"))
    api(project(":common:common-customobject"))
    api(project(":common:common-generator"))

    // Shaded dependencies
    api("com.fasterxml.jackson.core:jackson-annotations:2.9.7")
    api("com.fasterxml.jackson.core:jackson-core:2.9.7")
    api("com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:2.9.7")
    api('com.fasterxml.jackson.core:jackson-databind:2.16.1')
    api('org.yaml:snakeyaml:2.2')
    compileOnly 'org.projectlombok:lombok:1.18.32'
    annotationProcessor 'org.projectlombok:lombok:1.18.32'
}
